
package com.tk1.util;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://tu.tk1.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.AddResponse")
    @Action(input = "http://tu.tk1.com/HelloWorld/addRequest", output = "http://tu.tk1.com/HelloWorld/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.DeleteResponse")
    @Action(input = "http://tu.tk1.com/HelloWorld/deleteRequest", output = "http://tu.tk1.com/HelloWorld/deleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.SayHelloResponse")
    @Action(input = "http://tu.tk1.com/HelloWorld/sayHelloRequest", output = "http://tu.tk1.com/HelloWorld/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updat", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.Updat")
    @ResponseWrapper(localName = "updatResponse", targetNamespace = "http://tu.tk1.com/", className = "com.tk1.util.UpdatResponse")
    @Action(input = "http://tu.tk1.com/HelloWorld/updatRequest", output = "http://tu.tk1.com/HelloWorld/updatResponse")
    public String updat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
