
package com.tk1.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IShopping", targetNamespace = "http://tu.tk1.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IShopping {


    /**
     * 
     * @param products
     * @return
     *     returns com.tk1.tu.Products
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://tu.tk1.com/IShopping/saveOrderRequest", output = "http://tu.tk1.com/IShopping/saveOrderResponse")
    public Products saveOrder(
        @WebParam(name = "products", partName = "products")
        Products products);

    /**
     * 
     * @return
     *     returns com.tk1.tu.Products
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://tu.tk1.com/IShopping/availableProductsRequest", output = "http://tu.tk1.com/IShopping/availableProductsResponse")
    public Products availableProducts();

}
